sudo: false
language: java
jdk:
 - openjdk7
 - openjdk8
 - oraclejdk8
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
cache:
  directories:
    - $HOME/.m2/repository/org/owasp/dependency-check-data
before_cache:
  - rm -f $HOME/.m2/repository/org/owasp/dependency-check-data/3.0/dc.trace.db