language: java
sudo: false
#dist: trusty
jdk:
 - openjdk7
 - openjdk8
 - oraclejdk8
before_script:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
matrix:
  include:
    - dist: precise
    - dist: trusty
cache:
 directories:
  - $HOME/.m2
